name: Deploy Release

on: push
  # release:
  #   types: 
  #   - created 

jobs:
  buildAndDeploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          # - macos-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.x'
    - run : |
        echo $GOPATH
        sudo mkdir -p $GOPATH/mbtproject
        cd $GOPATH/mbtproject
    - uses: actions/checkout@master
    - run: |
        echo $GOPATH
        make build
    - name: Push Binaries
      uses: skx/github-action-publish-binaries@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: 'build/mbt*'
