name: Deploy Release

on:
  push
  # release:
  #   types: 
  #   - created 

jobs:
  buildAndDeploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          # - ubuntu-18.04
          # - macos-latest
          - windows-latest
        include:
          # - os: ubuntu-18.04
          #   artifact_name: mbt_linux_x86_64
          # - os: macos-latest
          #   artifact_name: mbt_darwin_x86_64
          - os: windows-latest
            artifact_name: mbt_windows_x86.zip

    steps:
    - uses: actions/checkout@master
      with:
        path: ./src

    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.x'

    - name: Install pkg-config
      if: runner.os == 'macOS'      
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew install pkg-config
        fi

    - name: Build MBT Linux/Mac
      env:
        GOPATH: ${{ github.workspace }}/..
        GOBIN: ${{ github.workspace }}/../bin
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        # Get the release version
        export VERSION=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH") 
        make build;

    - name: Build MBT Windows
      env:
        GOPATH: ${{ github.workspace }}/..
        GOBIN: ${{ github.workspace }}/../bin
      if: runner.os == 'Windows'
      run: |
        # choco install jq --force
        # cpan Path::Tiny
        # cpan Acme
        Start-Process -FilePath .\scripts\build_win.bat
        
    # - name: Set environment variables
    #   run: |
    #     echo ::set-env name=RELEASE_ID::$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")
    #     echo ::set-env name=GITHUB_REPOSITORY::$(echo "$GITHUB_REPOSITORY")

    # - name: Upload Release Asset
    #   id: upload-release-asset 
    #   uses: actions/upload-release-asset@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
    #     RELEASE_ID: ${{ env.RELEASE_ID }}
    #   with:
    #     upload_url: https://uploads.github.com/repos/${{ env.GITHUB_REPOSITORY }}/releases/${{ env.RELEASE_ID }}/assets?name=${{ matrix.artifact_name }}
    #     asset_path: ./build/${{ matrix.artifact_name }}
    #     asset_name: ${{ matrix.artifact_name }}
    #     asset_content_type: application/zip

    - name: Push Binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        chmod +x ./scripts/*
        ./scripts/upload_git.sh build/${{ matrix.artifact_name }}
